Repository Nupi-UMC/BackEnd, pull requests merged in 2025-01, with the labels that each got.

#2 ✨feat: 응답 통일, 예외 핸들러 세팅
  src/main/java/com/project/nupibe/global/apiPayload/CustomResponse.java
  src/main/java/com/project/nupibe/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/project/nupibe/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/project/nupibe/global/apiPayload/exception/CustomException.java
  src/main/java/com/project/nupibe/global/apiPayload/exception/handler/GlobalExceptionHandler.java
Labels: ✨feature

#4 ✨ feat: 도메인 별 Entity 작성
  src/main/java/com/project/nupibe/NupiBeApplication.java
  src/main/java/com/project/nupibe/domain/member/entity/Member.java
  src/main/java/com/project/nupibe/domain/member/entity/MemberRoute.java
  src/main/java/com/project/nupibe/domain/member/entity/MemberStore.java
  src/main/java/com/project/nupibe/domain/route/entity/Route.java
  src/main/java/com/project/nupibe/domain/route/entity/RouteStore.java
  src/main/java/com/project/nupibe/domain/store/entity/Store.java
  src/main/java/com/project/nupibe/global/entity/BaseEntity.java
Labels: ✨feature

#12 ✨ feat: 가게 조회(단일 가게, 주변 가게, 검색 조회)
  src/main/java/com/project/nupibe/domain/store/controller/StoreController.java
  src/main/java/com/project/nupibe/domain/store/converter/StoreConverter.java
  src/main/java/com/project/nupibe/domain/store/dto/response/StoreResponseDTO.java
  src/main/java/com/project/nupibe/domain/store/exception/code/StoreErrorCode.java
  src/main/java/com/project/nupibe/domain/store/exception/handler/StoreException.java
  src/main/java/com/project/nupibe/domain/store/repository/StoreRepositroy.java
  src/main/java/com/project/nupibe/domain/store/service/StoreQueryService.java
Labels: ✨feature

#13 ✨ feat: 경로 조회 , 경로 내 장소 목록 조회 API
  build.gradle
  src/main/java/com/project/nupibe/domain/route/controller/RouteController.java
  src/main/java/com/project/nupibe/domain/route/converter/RouteConverter.java
  src/main/java/com/project/nupibe/domain/route/dto/response/RouteDetailResDTO.java
  src/main/java/com/project/nupibe/domain/route/dto/response/RoutePlacesResDTO.java
  src/main/java/com/project/nupibe/domain/route/dto/response/RouteStoreDTO.java
  src/main/java/com/project/nupibe/domain/route/exception/RouteErrorCode.java
  src/main/java/com/project/nupibe/domain/route/exception/RouteException.java
  src/main/java/com/project/nupibe/domain/route/repository/RouteRepository.java
  src/main/java/com/project/nupibe/domain/route/service/query/RouteQueryService.java
  src/main/java/com/project/nupibe/domain/store/entity/Store.java
  src/main/java/com/project/nupibe/domain/store/repository/StoreRepository.java
Labels: ✨feature, ♻️refactor

#15 ✨ feat: 회원가입
  src/main/java/com/project/nupibe/domain/member/controller/AuthController.java
  src/main/java/com/project/nupibe/domain/member/dto/request/RequestSignupDto.java
  src/main/java/com/project/nupibe/domain/member/dto/request/RequestVerificationDto.java
  src/main/java/com/project/nupibe/domain/member/dto/response/ResponseVerificationDto.java
  src/main/java/com/project/nupibe/domain/member/redis/RedisService.java
  src/main/java/com/project/nupibe/domain/member/repository/MemberRepository.java
  src/main/java/com/project/nupibe/domain/member/service/AuthService.java
  src/main/java/com/project/nupibe/domain/member/service/VerificationService.java
  src/main/java/com/project/nupibe/global/config/SecurityConfig.java
Labels: ✨feature, ♻️refactor

#18 ✨ feat: 사용자 정보 조회(마이페이지,저장장소) + CORS
  src/main/java/com/project/nupibe/domain/member/controller/MypageController.java
  src/main/java/com/project/nupibe/domain/member/converter/MemberConverter.java
  src/main/java/com/project/nupibe/domain/member/dto/response/MypageResponseDTO.java
  src/main/java/com/project/nupibe/domain/member/exception/code/MemberErrorCode.java
  src/main/java/com/project/nupibe/domain/member/exception/handler/MemberException.java
  src/main/java/com/project/nupibe/domain/member/repository/MemberRepository.java
  src/main/java/com/project/nupibe/domain/member/service/MypageService.java
  src/main/java/com/project/nupibe/domain/store/repository/MemberStoreRepository.java
  src/main/java/com/project/nupibe/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/project/nupibe/global/config/CorsConfig.java
  src/main/java/com/project/nupibe/global/config/SwaggerConfig.java
Labels: ✨feature, ♻️refactor

#25 🐛fix: 빌드 에러 해결
  src/main/java/com/project/nupibe/domain/store/entity/Store.java
  src/main/java/com/project/nupibe/domain/store/repository/StoreRepository.java
Labels: 🐞bug, 🐛fix

#35 ✨ feat: 경로 검색 조회
  src/main/java/com/project/nupibe/domain/member/service/VerificationService.java
  src/main/java/com/project/nupibe/domain/route/controller/RouteController.java
  src/main/java/com/project/nupibe/domain/route/converter/RouteConverter.java
  src/main/java/com/project/nupibe/domain/route/dto/response/RouteDetailResDTO.java
  src/main/java/com/project/nupibe/domain/route/entity/Route.java
  src/main/java/com/project/nupibe/domain/route/repository/RouteRepository.java
  src/main/java/com/project/nupibe/domain/route/service/query/RouteQueryService.java
  src/main/java/com/project/nupibe/domain/store/repository/StoreRepository.java
Labels: ✨feature

#40 ♻️ refactor: 가게에서 장소로 명칭 변경(용어 정리)
  src/main/java/com/project/nupibe/domain/store/controller/StoreController.java
Labels: ♻️refactor

#41 🐛 fix: dto 변경
  dump.rdb
  src/main/java/com/project/nupibe/domain/member/controller/AuthController.java
  src/main/java/com/project/nupibe/domain/member/dto/response/ResponseSignupDto.java
Labels: 🐛fix

#50 ✨ feat: 장소,경로 북마크/좋아요 API + 경로 조회 API(특정 장소 포함, 사용자 저장)
  src/main/java/com/project/nupibe/domain/member/controller/MypageController.java
  src/main/java/com/project/nupibe/domain/member/converter/MemberConverter.java
  src/main/java/com/project/nupibe/domain/member/dto/response/MypageResponseDTO.java
  src/main/java/com/project/nupibe/domain/member/entity/RouteLike.java
  src/main/java/com/project/nupibe/domain/member/entity/StoreLike.java
  src/main/java/com/project/nupibe/domain/member/repository/MemberRouteRepository.java
  src/main/java/com/project/nupibe/domain/member/repository/RouteLikeRepository.java
  src/main/java/com/project/nupibe/domain/member/repository/StoreLikeRepository.java
  src/main/java/com/project/nupibe/domain/member/service/MypageService.java
  src/main/java/com/project/nupibe/domain/route/controller/RouteController.java
  src/main/java/com/project/nupibe/domain/route/converter/RouteConverter.java
  src/main/java/com/project/nupibe/domain/route/dto/response/RouteDetailResDTO.java
  src/main/java/com/project/nupibe/domain/route/entity/Route.java
  src/main/java/com/project/nupibe/domain/route/repository/RouteStoreRepository.java
  src/main/java/com/project/nupibe/domain/route/service/RouteCommandService.java
  src/main/java/com/project/nupibe/domain/store/controller/StoreController.java
  src/main/java/com/project/nupibe/domain/store/converter/StoreConverter.java
  src/main/java/com/project/nupibe/domain/store/dto/response/StoreResponseDTO.java
  src/main/java/com/project/nupibe/domain/store/entity/Store.java
  src/main/java/com/project/nupibe/domain/store/service/StoreCommandService.java
Labels: ✨feature, 🐛fix

#53 ♻️ refactor: 내 주변 장소 조회 postGIS 사용, 페이지네이션 수정
  src/main/java/com/project/nupibe/domain/route/controller/RouteController.java
  src/main/java/com/project/nupibe/domain/route/entity/RouteSearchQuery.java
  src/main/java/com/project/nupibe/domain/route/exception/RouteErrorCode.java
  src/main/java/com/project/nupibe/domain/route/repository/RouteRepository.java
  src/main/java/com/project/nupibe/domain/route/service/query/RouteQueryService.java
  src/main/java/com/project/nupibe/domain/store/controller/StoreController.java
  src/main/java/com/project/nupibe/domain/store/entity/Store.java
  src/main/java/com/project/nupibe/domain/store/entity/StoreSearchQuery.java
  src/main/java/com/project/nupibe/domain/store/exception/code/StoreErrorCode.java
  src/main/java/com/project/nupibe/domain/store/repository/StoreRepository.java
  src/main/java/com/project/nupibe/domain/store/repository/StoreRepositroy.java
  src/main/java/com/project/nupibe/domain/store/service/StoreCommandService.java
  src/main/java/com/project/nupibe/domain/store/service/StoreQueryService.java
Labels: ♻️refactor

#55 🐛fix: 빌드 에러 해결
  src/main/java/com/project/nupibe/domain/route/controller/RouteController.java
Labels: 🐛fix

#59 ♻️ Refactor: 회원가입 컨트롤러 변경
  src/main/java/com/project/nupibe/domain/member/controller/AuthController.java
  src/main/java/com/project/nupibe/domain/member/controller/SignupController.java
  src/main/java/com/project/nupibe/domain/member/dto/request/RequestSignupDto.java
  src/main/java/com/project/nupibe/domain/member/service/SignupService.java
  src/main/java/com/project/nupibe/global/config/SecurityConfig.java
Labels: ♻️refactor
